run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Print
      - fmt.Println

issues:
  exclude-rules:
    # Ignore some linters in test files
    - path: _test\.go
      linters:
        - errcheck

